name: Daily Reminder Trigger

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点，对应北京时间早上 8 点
  workflow_dispatch:     # 支持手动触发

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger /check endpoint
        run: |
          curl https://deadline-reminder.onrender.com/check
