name: Daily Reminder Trigger

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 1 点 UTC（北京时间 9 点）运行
  workflow_dispatch:    # 允许手动运行

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger daily check
        run: curl https://deadline-reminder.onrender.com/check
name: Daily Reminder Trigger

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点 UTC（对应北京时间早上 8 点）触发
  workflow_dispatch:      # 允许手动运行（可选）

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger /check endpoint
        run: curl https://deadline-reminder.onrender.com/check
